package domain;

public enum Spell {
	DAMAGE,
    HEAL,
    BOOSTHEALTH,
    BOOSTMP,
    BOOSTATTACK,
    BOOSTDEFENSE,
    BOOSTSPECIALATTACK,
    BOOSTSPECIALDEFENSE,
    LOWERATTACK,
    LOWERDEFENSE,
    LOWERSPECIALATTACK,
    LOWERSPECIALDEFENSE,
    SKIPTURN,
    DRAW,
    DISCARD,
    COLLECTCARD,
    DESTROYFIELD,
    RECOVERFIELD,
    RECOVERHAND,
    RECOVERDECK,
    DESTROYDECK,
    RECOVERMP
}
